#! /usr/bin/env python3
"""Static checking."""


# [ Imports ]
# [ -Third Party ]
import a_sync
# [ -Project ]
import static_checker


# [ Main ]
if __name__ == "__main__":
    a_sync.block(static_checker.main)
